version: "3"

name: ${DOCKER_PROJECT_NAME}
services:
  mysql80:
    platform: linux/amd64
    image: mysql:8.0.32
    container_name: ${MYSQL_CONTAINER_NAME}
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Seoul
    ports:
      - 3306:3306
